name: 日記の自動AIレビュー

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前0時（UTC）に実行
  workflow_dispatch:  # 手動実行用

jobs:
  review-diary:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴を取得

      - name: Python環境のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 依存パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub python-dotenv discord.py

      - name: 新しい日記エントリをチェックしてAIレビュー
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python .github/scripts/review_diary.py
